// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Tax.Portal.Controllers
{
    public partial class AccountController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Login()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Disassociate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disassociate);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Manage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExternalLogin()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLogin);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ExternalLoginCallback()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginCallback);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LinkLogin()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LinkLogin);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ExternalLoginConfirmation()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginConfirmation);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetPasswordFinalize()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordFinalize);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetPasswordCompleted()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordCompleted);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ListTrafficMonths()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListTrafficMonths);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ListTrafficCalls()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListTrafficCalls);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AccountProfileEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AccountProfileEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ChangeEmailAddressStart()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressStart);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChangeEmailAddressFinalize()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressFinalize);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChangeEmailAddressCompleted()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressCompleted);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Tax.Portal.Models.JsonpResult viRegister()
        {
            return new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viRegister);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Tax.Portal.Models.JsonpResult viPreregister()
        {
            return new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viPreregister);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Tax.Portal.Models.JsonpResult viResetPasswordStart()
        {
            return new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viResetPasswordStart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Tax.Portal.Models.JsonpResult viResetPasswordFinalize()
        {
            return new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viResetPasswordFinalize);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> MailAgain()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MailAgain);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Validate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Validate);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult ValidateSuccess()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ValidateSuccess);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult ValidateFailure()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ValidateFailure);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Login = "Login";
            public readonly string Preregister = "Preregister";
            public readonly string Register = "Register";
            public readonly string Disassociate = "Disassociate";
            public readonly string Manage = "Manage";
            public readonly string ExternalLogin = "ExternalLogin";
            public readonly string ExternalLoginCallback = "ExternalLoginCallback";
            public readonly string LinkLogin = "LinkLogin";
            public readonly string LinkLoginCallback = "LinkLoginCallback";
            public readonly string ExternalLoginConfirmation = "ExternalLoginConfirmation";
            public readonly string LogOff = "LogOff";
            public readonly string ExternalLoginFailure = "ExternalLoginFailure";
            public readonly string RemoveAccountList = "RemoveAccountList";
            public readonly string ResetPasswordStart = "ResetPasswordStart";
            public readonly string ResetPasswordFinalize = "ResetPasswordFinalize";
            public readonly string ResetPasswordCompleted = "ResetPasswordCompleted";
            public readonly string ListTrafficMonths = "ListTrafficMonths";
            public readonly string ListTrafficCalls = "ListTrafficCalls";
            public readonly string AccountProfileEdit = "AccountProfileEdit";
            public readonly string ChangeEmailAddressStart = "ChangeEmailAddressStart";
            public readonly string ChangeEmailAddressFinalize = "ChangeEmailAddressFinalize";
            public readonly string ChangeEmailAddressCompleted = "ChangeEmailAddressCompleted";
            public readonly string viRegister = "viRegister";
            public readonly string viPreregister = "viPreregister";
            public readonly string viResetPasswordStart = "viResetPasswordStart";
            public readonly string viResetPasswordFinalize = "viResetPasswordFinalize";
            public readonly string MailAgain = "MailAgain";
            public readonly string Validate = "Validate";
            public readonly string ValidateSuccess = "ValidateSuccess";
            public readonly string ValidateFailure = "ValidateFailure";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Login = "Login";
            public const string Preregister = "Preregister";
            public const string Register = "Register";
            public const string Disassociate = "Disassociate";
            public const string Manage = "Manage";
            public const string ExternalLogin = "ExternalLogin";
            public const string ExternalLoginCallback = "ExternalLoginCallback";
            public const string LinkLogin = "LinkLogin";
            public const string LinkLoginCallback = "LinkLoginCallback";
            public const string ExternalLoginConfirmation = "ExternalLoginConfirmation";
            public const string LogOff = "LogOff";
            public const string ExternalLoginFailure = "ExternalLoginFailure";
            public const string RemoveAccountList = "RemoveAccountList";
            public const string ResetPasswordStart = "ResetPasswordStart";
            public const string ResetPasswordFinalize = "ResetPasswordFinalize";
            public const string ResetPasswordCompleted = "ResetPasswordCompleted";
            public const string ListTrafficMonths = "ListTrafficMonths";
            public const string ListTrafficCalls = "ListTrafficCalls";
            public const string AccountProfileEdit = "AccountProfileEdit";
            public const string ChangeEmailAddressStart = "ChangeEmailAddressStart";
            public const string ChangeEmailAddressFinalize = "ChangeEmailAddressFinalize";
            public const string ChangeEmailAddressCompleted = "ChangeEmailAddressCompleted";
            public const string viRegister = "viRegister";
            public const string viPreregister = "viPreregister";
            public const string viResetPasswordStart = "viResetPasswordStart";
            public const string viResetPasswordFinalize = "viResetPasswordFinalize";
            public const string MailAgain = "MailAgain";
            public const string Validate = "Validate";
            public const string ValidateSuccess = "ValidateSuccess";
            public const string ValidateFailure = "ValidateFailure";
        }


        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Preregister s_params_Preregister = new ActionParamsClass_Preregister();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Preregister PreregisterParams { get { return s_params_Preregister; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Preregister
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Disassociate s_params_Disassociate = new ActionParamsClass_Disassociate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Disassociate DisassociateParams { get { return s_params_Disassociate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Disassociate
        {
            public readonly string loginProvider = "loginProvider";
            public readonly string providerKey = "providerKey";
        }
        static readonly ActionParamsClass_Manage s_params_Manage = new ActionParamsClass_Manage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Manage ManageParams { get { return s_params_Manage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Manage
        {
            public readonly string message = "message";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ExternalLogin s_params_ExternalLogin = new ActionParamsClass_ExternalLogin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExternalLogin ExternalLoginParams { get { return s_params_ExternalLogin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExternalLogin
        {
            public readonly string provider = "provider";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_ExternalLoginCallback s_params_ExternalLoginCallback = new ActionParamsClass_ExternalLoginCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExternalLoginCallback ExternalLoginCallbackParams { get { return s_params_ExternalLoginCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExternalLoginCallback
        {
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_LinkLogin s_params_LinkLogin = new ActionParamsClass_LinkLogin();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LinkLogin LinkLoginParams { get { return s_params_LinkLogin; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LinkLogin
        {
            public readonly string provider = "provider";
        }
        static readonly ActionParamsClass_ExternalLoginConfirmation s_params_ExternalLoginConfirmation = new ActionParamsClass_ExternalLoginConfirmation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExternalLoginConfirmation ExternalLoginConfirmationParams { get { return s_params_ExternalLoginConfirmation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExternalLoginConfirmation
        {
            public readonly string model = "model";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_ResetPasswordStart s_params_ResetPasswordStart = new ActionParamsClass_ResetPasswordStart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPasswordStart ResetPasswordStartParams { get { return s_params_ResetPasswordStart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPasswordStart
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ResetPasswordFinalize s_params_ResetPasswordFinalize = new ActionParamsClass_ResetPasswordFinalize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPasswordFinalize ResetPasswordFinalizeParams { get { return s_params_ResetPasswordFinalize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPasswordFinalize
        {
            public readonly string token = "token";
            public readonly string message = "message";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ResetPasswordCompleted s_params_ResetPasswordCompleted = new ActionParamsClass_ResetPasswordCompleted();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPasswordCompleted ResetPasswordCompletedParams { get { return s_params_ResetPasswordCompleted; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPasswordCompleted
        {
            public readonly string message = "message";
        }
        static readonly ActionParamsClass_ListTrafficMonths s_params_ListTrafficMonths = new ActionParamsClass_ListTrafficMonths();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListTrafficMonths ListTrafficMonthsParams { get { return s_params_ListTrafficMonths; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListTrafficMonths
        {
            public readonly string grid = "grid";
        }
        static readonly ActionParamsClass_ListTrafficCalls s_params_ListTrafficCalls = new ActionParamsClass_ListTrafficCalls();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListTrafficCalls ListTrafficCallsParams { get { return s_params_ListTrafficCalls; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListTrafficCalls
        {
            public readonly string grid = "grid";
            public readonly string userId = "userId";
            public readonly string monthId = "monthId";
        }
        static readonly ActionParamsClass_AccountProfileEdit s_params_AccountProfileEdit = new ActionParamsClass_AccountProfileEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AccountProfileEdit AccountProfileEditParams { get { return s_params_AccountProfileEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AccountProfileEdit
        {
            public readonly string Id = "Id";
            public readonly string message = "message";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ChangeEmailAddressStart s_params_ChangeEmailAddressStart = new ActionParamsClass_ChangeEmailAddressStart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeEmailAddressStart ChangeEmailAddressStartParams { get { return s_params_ChangeEmailAddressStart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeEmailAddressStart
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ChangeEmailAddressFinalize s_params_ChangeEmailAddressFinalize = new ActionParamsClass_ChangeEmailAddressFinalize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeEmailAddressFinalize ChangeEmailAddressFinalizeParams { get { return s_params_ChangeEmailAddressFinalize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeEmailAddressFinalize
        {
            public readonly string token = "token";
            public readonly string message = "message";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ChangeEmailAddressCompleted s_params_ChangeEmailAddressCompleted = new ActionParamsClass_ChangeEmailAddressCompleted();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeEmailAddressCompleted ChangeEmailAddressCompletedParams { get { return s_params_ChangeEmailAddressCompleted; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeEmailAddressCompleted
        {
            public readonly string message = "message";
        }
        static readonly ActionParamsClass_viRegister s_params_viRegister = new ActionParamsClass_viRegister();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_viRegister viRegisterParams { get { return s_params_viRegister; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_viRegister
        {
            public readonly string model = "model";
            public readonly string field = "field";
        }
        static readonly ActionParamsClass_viPreregister s_params_viPreregister = new ActionParamsClass_viPreregister();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_viPreregister viPreregisterParams { get { return s_params_viPreregister; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_viPreregister
        {
            public readonly string model = "model";
            public readonly string field = "field";
        }
        static readonly ActionParamsClass_viResetPasswordStart s_params_viResetPasswordStart = new ActionParamsClass_viResetPasswordStart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_viResetPasswordStart viResetPasswordStartParams { get { return s_params_viResetPasswordStart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_viResetPasswordStart
        {
            public readonly string model = "model";
            public readonly string field = "field";
        }
        static readonly ActionParamsClass_viResetPasswordFinalize s_params_viResetPasswordFinalize = new ActionParamsClass_viResetPasswordFinalize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_viResetPasswordFinalize viResetPasswordFinalizeParams { get { return s_params_viResetPasswordFinalize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_viResetPasswordFinalize
        {
            public readonly string model = "model";
            public readonly string field = "field";
        }
        static readonly ActionParamsClass_MailAgain s_params_MailAgain = new ActionParamsClass_MailAgain();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MailAgain MailAgainParams { get { return s_params_MailAgain; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MailAgain
        {
            public readonly string loginname = "loginname";
        }
        static readonly ActionParamsClass_Validate s_params_Validate = new ActionParamsClass_Validate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Validate ValidateParams { get { return s_params_Validate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Validate
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ValidateSuccess s_params_ValidateSuccess = new ActionParamsClass_ValidateSuccess();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateSuccess ValidateSuccessParams { get { return s_params_ValidateSuccess; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateSuccess
        {
            public readonly string message = "message";
        }
        static readonly ActionParamsClass_ValidateFailure s_params_ValidateFailure = new ActionParamsClass_ValidateFailure();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateFailure ValidateFailureParams { get { return s_params_ValidateFailure; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateFailure
        {
            public readonly string message = "message";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChangePasswordPartial = "_ChangePasswordPartial";
                public readonly string _ExternalLoginsListPartial = "_ExternalLoginsListPartial";
                public readonly string _RemoveAccountPartial = "_RemoveAccountPartial";
                public readonly string _SetPasswordPartial = "_SetPasswordPartial";
                public readonly string AccountProfileEdit = "AccountProfileEdit";
                public readonly string ExternalLoginConfirmation = "ExternalLoginConfirmation";
                public readonly string ExternalLoginFailure = "ExternalLoginFailure";
                public readonly string Login = "Login";
                public readonly string Manage = "Manage";
                public readonly string PreRegister = "PreRegister";
                public readonly string Register = "Register";
                public readonly string ResetPasswordFinalize = "ResetPasswordFinalize";
                public readonly string ResetPasswordStart = "ResetPasswordStart";
                public readonly string ValidateFailure = "ValidateFailure";
                public readonly string ValidateSuccess = "ValidateSuccess";
            }
            public readonly string _ChangePasswordPartial = "~/Views/Account/_ChangePasswordPartial.cshtml";
            public readonly string _ExternalLoginsListPartial = "~/Views/Account/_ExternalLoginsListPartial.cshtml";
            public readonly string _RemoveAccountPartial = "~/Views/Account/_RemoveAccountPartial.cshtml";
            public readonly string _SetPasswordPartial = "~/Views/Account/_SetPasswordPartial.cshtml";
            public readonly string AccountProfileEdit = "~/Views/Account/AccountProfileEdit.cshtml";
            public readonly string ExternalLoginConfirmation = "~/Views/Account/ExternalLoginConfirmation.cshtml";
            public readonly string ExternalLoginFailure = "~/Views/Account/ExternalLoginFailure.cshtml";
            public readonly string Login = "~/Views/Account/Login.cshtml";
            public readonly string Manage = "~/Views/Account/Manage.cshtml";
            public readonly string PreRegister = "~/Views/Account/PreRegister.cshtml";
            public readonly string Register = "~/Views/Account/Register.cshtml";
            public readonly string ResetPasswordFinalize = "~/Views/Account/ResetPasswordFinalize.cshtml";
            public readonly string ResetPasswordStart = "~/Views/Account/ResetPasswordStart.cshtml";
            public readonly string ValidateFailure = "~/Views/Account/ValidateFailure.cshtml";
            public readonly string ValidateSuccess = "~/Views/Account/ValidateSuccess.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AccountController : Tax.Portal.Controllers.AccountController
    {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        public override System.Web.Mvc.ActionResult Login(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, returnUrl);
            return callInfo;
        }

        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.LoginViewModel model, string returnUrl);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Login(Tax.Portal.Models.LoginViewModel model, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, model, returnUrl);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void PreregisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Preregister()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Preregister);
            PreregisterOverride(callInfo);
            return callInfo;
        }

        partial void PreregisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.PreRegisterViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Preregister(Tax.Portal.Models.PreRegisterViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Preregister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PreregisterOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Register()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            RegisterOverride(callInfo);
            return callInfo;
        }

        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.RegisterViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Register(Tax.Portal.Models.RegisterViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RegisterOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void DisassociateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string loginProvider, string providerKey);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Disassociate(string loginProvider, string providerKey)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Disassociate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loginProvider", loginProvider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "providerKey", providerKey);
            DisassociateOverride(callInfo, loginProvider, providerKey);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ManageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Controllers.AccountController.ManageMessageId? message);

        public override System.Web.Mvc.ActionResult Manage(Tax.Portal.Controllers.AccountController.ManageMessageId? message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ManageOverride(callInfo, message);
            return callInfo;
        }

        partial void ManageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ManageUserViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Manage(Tax.Portal.Models.ManageUserViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ManageOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ExternalLoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string provider, string returnUrl);

        public override System.Web.Mvc.ActionResult ExternalLogin(string provider, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLogin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ExternalLoginOverride(callInfo, provider, returnUrl);
            return callInfo;
        }

        partial void ExternalLoginCallbackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ExternalLoginCallback(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ExternalLoginCallbackOverride(callInfo, returnUrl);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void LinkLoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string provider);

        public override System.Web.Mvc.ActionResult LinkLogin(string provider)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LinkLogin);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "provider", provider);
            LinkLoginOverride(callInfo, provider);
            return callInfo;
        }

        partial void LinkLoginCallbackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> LinkLoginCallback()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LinkLoginCallback);
            LinkLoginCallbackOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ExternalLoginConfirmationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ExternalLoginConfirmationViewModel model, string returnUrl);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ExternalLoginConfirmation(Tax.Portal.Models.ExternalLoginConfirmationViewModel model, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginConfirmation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ExternalLoginConfirmationOverride(callInfo, model, returnUrl);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void LogOffOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult LogOff()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOff);
            LogOffOverride(callInfo);
            return callInfo;
        }

        partial void ExternalLoginFailureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ExternalLoginFailure()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExternalLoginFailure);
            ExternalLoginFailureOverride(callInfo);
            return callInfo;
        }

        partial void RemoveAccountListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult RemoveAccountList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveAccountList);
            RemoveAccountListOverride(callInfo);
            return callInfo;
        }

        partial void ResetPasswordStartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ResetPasswordStart()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordStart);
            ResetPasswordStartOverride(callInfo);
            return callInfo;
        }

        partial void ResetPasswordStartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ResetPasswordStartViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResetPasswordStart(Tax.Portal.Models.ResetPasswordStartViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordStart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResetPasswordStartOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ResetPasswordFinalizeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string token, string message);

        public override System.Web.Mvc.ActionResult ResetPasswordFinalize(string token, string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordFinalize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "token", token);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ResetPasswordFinalizeOverride(callInfo, token, message);
            return callInfo;
        }

        partial void ResetPasswordFinalizeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ResetPasswordFinalizeViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ResetPasswordFinalize(Tax.Portal.Models.ResetPasswordFinalizeViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordFinalize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ResetPasswordFinalizeOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ResetPasswordCompletedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string message);

        public override System.Web.Mvc.ActionResult ResetPasswordCompleted(string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPasswordCompleted);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ResetPasswordCompletedOverride(callInfo, message);
            return callInfo;
        }

        partial void ListTrafficMonthsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, JQGrid.Helpers.GridSettings grid);

        public override System.Web.Mvc.JsonResult ListTrafficMonths(JQGrid.Helpers.GridSettings grid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListTrafficMonths);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "grid", grid);
            ListTrafficMonthsOverride(callInfo, grid);
            return callInfo;
        }

        partial void ListTrafficCallsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, JQGrid.Helpers.GridSettings grid, string userId, System.Guid monthId);

        public override System.Web.Mvc.JsonResult ListTrafficCalls(JQGrid.Helpers.GridSettings grid, string userId, System.Guid monthId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListTrafficCalls);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "grid", grid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "monthId", monthId);
            ListTrafficCallsOverride(callInfo, grid, userId, monthId);
            return callInfo;
        }

        partial void AccountProfileEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string Id, string message);

        public override System.Web.Mvc.ActionResult AccountProfileEdit(string Id, string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AccountProfileEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            AccountProfileEditOverride(callInfo, Id, message);
            return callInfo;
        }

        partial void AccountProfileEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.AccountProfileViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> AccountProfileEdit(Tax.Portal.Models.AccountProfileViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AccountProfileEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AccountProfileEditOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ChangeEmailAddressStartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ChangeEmailAddressStartViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ChangeEmailAddressStart(Tax.Portal.Models.ChangeEmailAddressStartViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressStart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ChangeEmailAddressStartOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ChangeEmailAddressFinalizeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string token, string message);

        public override System.Web.Mvc.ActionResult ChangeEmailAddressFinalize(string token, string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressFinalize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "token", token);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ChangeEmailAddressFinalizeOverride(callInfo, token, message);
            return callInfo;
        }

        partial void ChangeEmailAddressFinalizeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Tax.Portal.Models.ChangeEmailAddressFinalizeViewModel model);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> ChangeEmailAddressFinalize(Tax.Portal.Models.ChangeEmailAddressFinalizeViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressFinalize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ChangeEmailAddressFinalizeOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ChangeEmailAddressCompletedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string message);

        public override System.Web.Mvc.ActionResult ChangeEmailAddressCompleted(string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeEmailAddressCompleted);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ChangeEmailAddressCompletedOverride(callInfo, message);
            return callInfo;
        }

        partial void viRegisterOverride(T4MVC_Tax_Portal_Models_JsonpResult callInfo, Tax.Portal.Models.RegisterViewModel model, string field);

        public override Tax.Portal.Models.JsonpResult viRegister(Tax.Portal.Models.RegisterViewModel model, string field)
        {
            var callInfo = new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viRegister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "field", field);
            viRegisterOverride(callInfo, model, field);
            return callInfo;
        }

        partial void viPreregisterOverride(T4MVC_Tax_Portal_Models_JsonpResult callInfo, Tax.Portal.Models.PreRegisterViewModel model, string field);

        public override Tax.Portal.Models.JsonpResult viPreregister(Tax.Portal.Models.PreRegisterViewModel model, string field)
        {
            var callInfo = new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viPreregister);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "field", field);
            viPreregisterOverride(callInfo, model, field);
            return callInfo;
        }

        partial void viResetPasswordStartOverride(T4MVC_Tax_Portal_Models_JsonpResult callInfo, Tax.Portal.Models.ResetPasswordStartViewModel model, string field);

        public override Tax.Portal.Models.JsonpResult viResetPasswordStart(Tax.Portal.Models.ResetPasswordStartViewModel model, string field)
        {
            var callInfo = new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viResetPasswordStart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "field", field);
            viResetPasswordStartOverride(callInfo, model, field);
            return callInfo;
        }

        partial void viResetPasswordFinalizeOverride(T4MVC_Tax_Portal_Models_JsonpResult callInfo, Tax.Portal.Models.ResetPasswordFinalizeViewModel model, string field);

        public override Tax.Portal.Models.JsonpResult viResetPasswordFinalize(Tax.Portal.Models.ResetPasswordFinalizeViewModel model, string field)
        {
            var callInfo = new T4MVC_Tax_Portal_Models_JsonpResult(Area, Name, ActionNames.viResetPasswordFinalize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "field", field);
            viResetPasswordFinalizeOverride(callInfo, model, field);
            return callInfo;
        }

        partial void MailAgainOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string loginname);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> MailAgain(string loginname)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MailAgain);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loginname", loginname);
            MailAgainOverride(callInfo, loginname);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ValidateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Validate(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Validate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ValidateOverride(callInfo, id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void ValidateSuccessOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string message);

        public override System.Web.Mvc.ViewResult ValidateSuccess(string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ValidateSuccess);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ValidateSuccessOverride(callInfo, message);
            return callInfo;
        }

        partial void ValidateFailureOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string message);

        public override System.Web.Mvc.ViewResult ValidateFailure(string message)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ValidateFailure);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ValidateFailureOverride(callInfo, message);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
