// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SinoszController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
                public readonly string List = "List";
                public readonly string New = "New";
                public readonly string Parameter = "Parameter";
                public readonly string Print = "Print";
                public readonly string PrintCommContract = "PrintCommContract";
                public readonly string PrintDevContract = "PrintDevContract";
            }
            public readonly string Edit = "~/Views/Sinosz/Edit.cshtml";
            public readonly string Index = "~/Views/Sinosz/Index.cshtml";
            public readonly string List = "~/Views/Sinosz/List.cshtml";
            public readonly string New = "~/Views/Sinosz/New.cshtml";
            public readonly string Parameter = "~/Views/Sinosz/Parameter.cshtml";
            public readonly string Print = "~/Views/Sinosz/Print.cshtml";
            public readonly string PrintCommContract = "~/Views/Sinosz/PrintCommContract.cshtml";
            public readonly string PrintDevContract = "~/Views/Sinosz/PrintDevContract.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
