// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class UserMailerController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string ResetPassword = "ResetPassword";
                public readonly string ResetPasswordCompleted = "ResetPasswordCompleted";
                public readonly string RulesEmail = "RulesEmail";
                public readonly string ScheduleClosed = "ScheduleClosed";
                public readonly string ValidateEmail = "ValidateEmail";
                public readonly string Welcome = "Welcome";
                public readonly string WithDeviceElectedEmail = "WithDeviceElectedEmail";
                public readonly string WithoutDeviceElectedEmail = "WithoutDeviceElectedEmail";
            }
            public readonly string _Layout = "~/Views/UserMailer/_Layout.cshtml";
            public readonly string ResetPassword = "~/Views/UserMailer/ResetPassword.cshtml";
            public readonly string ResetPasswordCompleted = "~/Views/UserMailer/ResetPasswordCompleted.cshtml";
            public readonly string RulesEmail = "~/Views/UserMailer/RulesEmail.cshtml";
            public readonly string ScheduleClosed = "~/Views/UserMailer/ScheduleClosed.cshtml";
            public readonly string ValidateEmail = "~/Views/UserMailer/ValidateEmail.cshtml";
            public readonly string Welcome = "~/Views/UserMailer/Welcome.cshtml";
            public readonly string WithDeviceElectedEmail = "~/Views/UserMailer/WithDeviceElectedEmail.cshtml";
            public readonly string WithoutDeviceElectedEmail = "~/Views/UserMailer/WithoutDeviceElectedEmail.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
