// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tax.Portal.AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class FelhasznaloiProfilFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Profil.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("hu-HU"), "Felhasználói profil", "Ahhoz, hogy használni tudjam a Kontakt Portált, mint Ügyfél, tudnom kell\r\nregiszt" +
                    "rálni,\r\nbejelentkezni és kijelentkezni,\r\nadataimat módosítani.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Felhasználói profil")))
            {
                Tax.Portal.AcceptanceTests.FelhasznaloiProfilFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void Regisztracio(string felhasznaloNev, string emailCim, string jelszo, string jelszoMegegyszer, string eredmeny, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Regisztráció", exampleTags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("a regisztrációs oldal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 9
 testRunner.When(string.Format("megadom a {0} {1} {2} és {3} regisztrációs adatot", felhasznaloNev, emailCim, jelszo, jelszoMegegyszer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 10
 testRunner.Then(string.Format("a rendszer tájékoztat a regisztráció {0}-éről", eredmeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Regisztráció")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'tesztfelhasznalo\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:felhasználó név", "\'tesztfelhasznalo\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Email cím", "\'teszt@egroup.hu\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:jelszó", "\'pas1234PAS\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:jelszó mégegyszer", "\'pas1234PAS\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:eredmény", "\'sikeres\'")]
        public virtual void Regisztracio_Tesztfelhasznalo()
        {
            this.Regisztracio("\'tesztfelhasznalo\'", "\'teszt@egroup.hu\'", "\'pas1234PAS\'", "\'pas1234PAS\'", "\'sikeres\'", ((string[])(null)));
        }
        
        public virtual void Bejelentkezes(string felhasznaloNev, string jelszo, string eredmeny, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Bejelentkezés", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("a bejelentkezési oldal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 20
 testRunner.When(string.Format("megadom a {0} és {1} bejelentkezési adatot", felhasznaloNev, jelszo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 21
 testRunner.Then(string.Format("a rendszer tájékoztat a bejelentkezés {0}-éről", eredmeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Bejelentkezés")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'tesztfelhasznalo\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:felhasználó név", "\'tesztfelhasznalo\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:jelszó", "\'pas1234PAS\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:eredmény", "\'sikeres\'")]
        public virtual void Bejelentkezes_Tesztfelhasznalo()
        {
            this.Bejelentkezes("\'tesztfelhasznalo\'", "\'pas1234PAS\'", "\'sikeres\'", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Kijelentkezés")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        public virtual void Kijelentkezes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kijelentkezés", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("a bejelentkezett felhasználó", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 29
 testRunner.When("kijelentkezem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 30
 testRunner.Then("a rendszer tájékoztat a kijelentkezésről", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void JelszovisszaallitasKezdemenyezese(string emailCim, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Jelszóvisszaállítás kezdeményezése", exampleTags);
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("a jelszóvisszaállítási oldal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 34
 testRunner.When(string.Format("megadom a {0}-et", emailCim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 35
 testRunner.And("kezdeményezem a jelszó visszaállítást", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "És ");
#line 36
 testRunner.Then("a rendszer tájékoztat a jelszóvisszaállítás teendőiről", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Jelszóvisszaállítás kezdeményezése")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'teszt@egroup.hu\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:email cím", "\'teszt@egroup.hu\'")]
        public virtual void JelszovisszaallitasKezdemenyezese_TesztEgroup_Hu()
        {
            this.JelszovisszaallitasKezdemenyezese("\'teszt@egroup.hu\'", ((string[])(null)));
        }
        
        public virtual void JelszovisszaallitasVegrehajtasa(string token, string jelszo1, string jelszo2, string eredmeny, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Jelszóvisszaállítás végrehajtása", exampleTags);
#line 42
this.ScenarioSetup(scenarioInfo);
#line 43
 testRunner.Given(string.Format("a jelszóvisszaállítási {0}", token), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 44
 testRunner.When(string.Format("megadom a {0} és {1} jelszó adatot", jelszo1, jelszo2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 45
 testRunner.And("megerősítem a jelszó visszaállítást", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "És ");
#line 46
 testRunner.Then(string.Format("a rendszer tájékoztat a jelszóvisszaállítás {0}-ről", eredmeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Jelszóvisszaállítás végrehajtása")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'123\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:token", "\'123\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:jelszó1", "\'pas1234PAS\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:jelszó2", "\'pas1234PAS\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:eredmény", "\'sikeres\'")]
        public virtual void JelszovisszaallitasVegrehajtasa_123()
        {
            this.JelszovisszaallitasVegrehajtasa("\'123\'", "\'pas1234PAS\'", "\'pas1234PAS\'", "\'sikeres\'", ((string[])(null)));
        }
        
        public virtual void EmailcimValtoztatasKezdemenyezese(string emailCim, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Emailcím változtatás kezdeményezése", exampleTags);
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("a bejelentkezett felhasználó az emailcím változtatása oldalon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 54
 testRunner.When(string.Format("megadom az {0} email címet", emailCim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 55
 testRunner.And("kezdeményzem az email cím megváltoztatását", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "És ");
#line 56
 testRunner.Then("a rendszer tájékoztat az email cím változtatás teendőiről", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Emailcím változtatás kezdeményezése")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'teszt@egroup.hu\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:email cím", "\'teszt@egroup.hu\'")]
        public virtual void EmailcimValtoztatasKezdemenyezese_TesztEgroup_Hu()
        {
            this.EmailcimValtoztatasKezdemenyezese("\'teszt@egroup.hu\'", ((string[])(null)));
        }
        
        public virtual void EmailcimValtoztatasVegrehajtasa(string token, string eredmeny, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Emailcím változtatás végrehajtása", exampleTags);
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given(string.Format("az email cím változtatási {0}", token), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 64
 testRunner.When("megerősítem az email cím változtatást", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 65
 testRunner.Then(string.Format("a rendszer tájékoztat az email cím változtatás {0}-ről", eredmeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Emailcím változtatás végrehajtása")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'123\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:token", "\'123\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:eredmény", "\'sikeres\'")]
        public virtual void EmailcimValtoztatasVegrehajtasa_123()
        {
            this.EmailcimValtoztatasVegrehajtasa("\'123\'", "\'sikeres\'", ((string[])(null)));
        }
        
        public virtual void EgyebProfiladatokValtoztatasa(string sinosz_Tagsag, string tagsagiAzonosito, string szuletesiDatum, string kommunikaciosIgeny, string eszkozigeny, string eredmeny, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Egyéb profiladatok változtatása", exampleTags);
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("a bejelentkezett felhasználó a profiladatok változtatása oldalon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Adott ");
#line 73
 testRunner.When(string.Format("megadom a {0}, {1}, {2}, {3} és {4} adatot", sinosz_Tagsag, tagsagiAzonosito, szuletesiDatum, kommunikaciosIgeny, eszkozigeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Ha ");
#line 74
 testRunner.Then(string.Format("a rendszer tájékoztat az adatváltoztatás {0}-éről", eredmeny), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Akkor ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Egyéb profiladatok változtatása")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Felhasználói profil")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "\'igen\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Sinosz-tagság", "\'igen\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Tagsági azonosító", "\'12345\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Születési dátum", "\'1990.01.01\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Kommunikációs igény", "\'igen\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Eszközigény", "\'igen\'")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:eredmény", "\'sikeres\'")]
        public virtual void EgyebProfiladatokValtoztatasa_Igen()
        {
            this.EgyebProfiladatokValtoztatasa("\'igen\'", "\'12345\'", "\'1990.01.01\'", "\'igen\'", "\'igen\'", "\'sikeres\'", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
