// <auto-generated />
namespace Tax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class fimerge2014030601 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fimerge2014030601));
        
        string IMigrationMetadata.Id
        {
            get { return "201403060950175_fi-merge-20140306-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
