// <auto-generated />
namespace Tax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class file_typefinaly2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(file_typefinaly2));
        
        string IMigrationMetadata.Id
        {
            get { return "201401211219218_file_type finaly2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
