// <auto-generated />
namespace Tax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class iosproductiontosetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iosproductiontosetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201405271217020_ios production to setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
