// <auto-generated />
namespace Tax.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class PBXSync_ExtensionValidityRange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PBXSync_ExtensionValidityRange));
        
        string IMigrationMetadata.Id
        {
            get { return "201401241159018_PBXSync_ExtensionValidityRange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
